apiVersion: v1
kind: Pod
metadata:
  name: two
  labels:
    app: two
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nginx
    image: nginxinc/nginx-unprivileged:1.27-alpine
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: 2
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
